apiVersion: v1
kind: Namespace
metadata:
  name: devops-lambda-ping-pong
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-ping-pong-dep
  namespace: devops-lambda-ping-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-service
  template:
    metadata:
      labels:
        app: k8s-service
    spec:
      containers:
      - name: k8s-service
        image: umairnaushad/k8s-ping-pong:1.0.1
        env:
        - name: SERVICE_URL
          value: "http://localhost:32104/"
        resources: 
          requests:
            cpu: "600m"
            memory: "1000Mi"
          limits:
            cpu: "1000m"
            memory: "2000Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-ping-pong-svc
  namespace: devops-lambda-ping-pong
spec:
  selector:
    app: k8s-service
  type: NodePort
  ports:
    - name: http
      port: 5003
      targetPort: 5000
      nodePort: 32103
