AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-ping-pong
  Sample SAM Template for lambda-ping-pong

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  PingFunction:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
        CodeUri: ping_pong/
        Handler: app.lambda_handler_ping
        Runtime: python3.7
        Environment:
          Variables:
            SERVICE_URL: "http://localhost:32103/"
        Events:
          Pong:
            Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
            Properties:
              Path: /ping
              Method: get
  PongFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ping_pong/
      Handler: app.lambda_handler_pong
      Runtime: python3.7
      Events:
        Pong:
          Type: Api
          Properties:
            Path: /pong
            Method: post
  AboutFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ping_pong/
      Handler: app.lambda_handler_default
      Runtime: python3.7
      Events:
        Pong:
          Type: Api
          Properties:
            Path: /
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PingPongApi:
    Description: "API Gateway endpoint URL for Prod stage for pong function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/pong/"
  PingPongFunction:
    Description: "Ping pong Lambda Function ARN"
    Value: !GetAtt PongFunction.Arn
  PingPongFunctionIamRole:
    Description: "Implicit IAM Role created for Ping Pong function"
    Value: !GetAtt PongFunctionRole.Arn
