apiVersion: v1
kind: Namespace
metadata:
  name: devops
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-1-ping-pong-dep
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-1
  template:
    metadata:
      labels:
        app: service-1
    spec:
      containers:
      - name: service-1
        image: umairnaushad/service-1-ping-pong:1.0.0
        resources: 
          requests:
            cpu: "500m"
            memory: "1000Mi"
          limits:
            cpu: "1000m"
            memory: "2000Mi"
        readinessProbe:
          httpGet:
            path: /about
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 18
        livenessProbe:
          httpGet:
            path: /about
            port: 5000
          initialDelaySeconds: 180
          periodSeconds: 10
          failureThreshold: 6
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: service-1-ping-pong-svc
  namespace: devops
spec:
  selector:
    app: service-1
  type: NodePort
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 32050
